using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System.Linq;
using Photon.Realtime;
using TMPro;
using Photon.Pun;
using UnityEngine.SceneManagement;
using System.IO;

namespace Arashmup
{
    public class TextReplacer : MonoBehaviour
    {
        TMP_Text Text;

        public StringVariable Variable;

        public bool AlwaysUpdate;

        private void OnEnable()
        {
            Text = GetComponent<TMP_Text>();
            Text.text = Variable.Value;
        }

        private void Update()
        {
            if (AlwaysUpdate)
            {
                Text.text = Variable.Value;
            }
        }
    }
}